[workspace]
members = ["crates/ferxium-core", "crates/ferxium-service", "crates/ferxium-cli", "apps/desktop/src-tauri"]
default-members = ["crates/ferxium-core", "crates/ferxium-service", "crates/ferxium-cli"]
resolver = "2"

[workspace.package]
version = "0.1.4"
edition = "2024"
rust-version = "1.90"
license = "MIT"

[workspace.dependencies]
anyhow = "1"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
tokio = { version = "1", features = ["rt-multi-thread", "macros", "signal", "sync", "time", "net"] }
sha2 = "0.10"
hex = "0.4"
uuid = { version = "1", features = ["v4", "serde"] }
chrono = { version = "0.4", features = ["serde"] }
reqwest = { version = "0.12", default-features = false, features = ["json", "rustls-tls", "stream"] }
tracing = "0.1"
tracing-subscriber = { version = "0.3", features = ["env-filter"] }
clap = { version = "4", features = ["derive"] }

[profile.release]
lto = "thin"
codegen-units = 1
strip = true

[workspace.lints.clippy]
undocumented_unsafe_blocks = "deny"
