import type { Status } from './types';
const now = new Date().toISOString();
export const demo: Status = {
  version: '0.1.0',
  protection_enabled: true,
  watcher_active: true,
  watched_roots: ['C:\\Users\\You\\Downloads', 'C:\\Users\\You\\Desktop'],
  dropped_events: 0,
  yara_enabled: true,
  signature_version: 1,
  scanned_total: 128492,
  process_count: 142,
  network_received: 8391923,
  network_transmitted: 912829,
  established_connections: 18,
  threats: [],
  quarantine: [],
  scan: null,
  history: [
    {
      id: 'demo-last',
      kind: 'quick',
      state: 'completed',
      scanned: 18429,
      total_files: 18429,
      skipped: 18,
      errors: 0,
      threats: 0,
      current_path: null,
      started_at: now,
      finished_at: now,
      elapsed_seconds: 42,
      estimated_remaining_seconds: null,
    },
  ],
  activity: [
    { at: now, level: 'info', message: 'Quick scan complete. No detections in checked files.' },
    { at: now, level: 'info', message: 'Native file monitoring is watching 2 folders.' },
    { at: now, level: 'info', message: 'Signature database v1 is ready.' },
  ],
  config: {
    protection_enabled: true,
    watch_paths: ['C:\\Users\\You\\Downloads', 'C:\\Users\\You\\Desktop'],
    exclusions: [],
    allowed_hashes: [],
    max_file_bytes: 67108864,
    heuristics_enabled: true,
    scan_interval_hours: null,
    update_interval_hours: null,
    update_manifest_url: null,
    update_public_key: null,
    cloud_lookup_enabled: false,
  },
};
